CREATE TABLE IF NOT EXISTS prepayment_approvals (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    approval_no VARCHAR(30) NOT NULL,
    supplier_id BIGINT NOT NULL,
    applied_amount DECIMAL(19,2) NOT NULL,
    actual_amount DECIMAL(19,2),
    payer_name VARCHAR(100),
    payer_account VARCHAR(100),
    payer_bank VARCHAR(100),
    payee_name VARCHAR(100),
    payee_account VARCHAR(100),
    payee_bank VARCHAR(100),
    contact_name VARCHAR(100),
    contact_phone VARCHAR(20),
    attachments TEXT,
    apply_remark TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    bank_receipt_no VARCHAR(100),
    payment_voucher TEXT,
    approved_by VARCHAR(100),
    approved_at DATETIME,
    cashier_by VARCHAR(100),
    cashier_at DATETIME,
    reject_reason TEXT,
    created_by VARCHAR(100),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX uk_approval_no (approval_no),
    INDEX idx_supplier_id (supplier_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_prepayment_approvals_supplier_id FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
